music_app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :bands
end

music_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

music_app/app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :bigint(8)        not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  image      :string           not null
#

class Band < ApplicationRecord
  validates :name, :image, presence: true, uniqueness: true
end

music_app/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint(8)        not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  validates :email, :session_token, presence: true, uniqueness: true
  validates :password_digest, presence: true
  validates :password, presence: true, if: :password
  validates :password, length: { minimum: 6, allow_nil: true }

  attr_reader :password

  after_initialize :ensure_session_token

  def self.find_by_credentials(attempted_email, attempted_password)
    user = User.find_by(email: attempted_email)
    return nil unless user && user.is_password?(attempted_password)
    user
  end

  def reset_session_token!
    self.update!(session_token: User::generate_session_token)
    self.session_token
  end

  def password=(new_password)
    @password = new_password
    self.password_digest = BCrypt::Password.create(new_password)
  end

  def is_password?(attempted_password)
    encrypted = BCrypt::Password.new(self.password_digest)
    encrypted.is_password?(attempted_password)
  end

  private

  def ensure_session_token
    self.session_token ||= User::generate_session_token
  end

  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end
end

music_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user

  def log_in!(user)
    session[:session_token] = user.reset_session_token!
  end

  def current_user
    user = User.find_by(session_token: session[:session_token])
  end

  def logged_in?(user)
    !!current_user
  end

  def ensure_logged_in
    redirect_to new_session_url unless logged_in?
  end

  def log_out!
    current_user.reset_session_token!
    session[:session_token] = nil
    redirect_to new_session_url
  end
end

music_app/app/controllers/bands_controller.rb
class BandsController < ApplicationController

  def index
    render :index
  end

  def new
    @band = Band.new
    render :new
  end

  def create
    @band = Band.new(band_params)

    if @band.save
      redirect_to bands_url
    else
      flash.now[:errors] = @band.errors.full_messages
      render :new
    end
  end

  def edit
    @band = Band.find(params[:id])
    render :edit
  end

  def update
    @band = Band.find(params[:id])
    if @band.update(band_params)
      redirect_to band_url(@band)
    else
      flash[:errors] = @band.errors.full_messages
      render :edit
    end
  end

  def show
    @band = Band.find(params[:id])
    render :show
  end

  def destroy
    band = Band.find(params[:id])
    band.destroy
    redirect_to bands_url
  end

  private

  def band_params
    params.require(:band).permit(:name, :image)
  end
end

music_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
    render :new
  end

  def create
    user = User.find_by_credentials(
      params[:user][:email],
      params[:user][:password]
    )

    if user
      log_in!(user)
      redirect_to user_url
    else
      @user = User.new(email: params[:user][:email])
      flash.now[:errors] = ['Invalid username or password']
      render :new
    end
  end

  def destroy
    log_out!
  end
end

music_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      log_in!(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      # redirect_to new_user_url
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    render :show
  end

  private
  def user_params
    params.require(:user).permit(:email, :password)
  end
end

music_app/app/helpers/application_helper.rb
module ApplicationHelper
end

music_app/app/views/bands/_form.html.erb
<% if editing %>
  <% title = "Edit Your Band!" %>
  <% action = band_url(band) %>
  <% submission = "Edit Band!" %>
<% else %>
  <% title = "Upload Your Band!" %>
  <% action = bands_url %>
  <% submission = "Upload Band!" %>
<% end %>

<h2><%= title %></h2>

<% if flash[:errors] %>
<ul>
  <% flash[:errors].each do |error| %>
  <li><%= error %></li>
  <% end %>
</ul>
<% end %>

<form action="<%= action %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="_method" value="patch">
  <p>
    <label class="upload_band_label" for="band_name">Your Band's Name: </label>
    <input id="band_name" type="text" name="band[name]" value="<%= @band.name %>">
  </p>

  <br><br>

  <p>
    <label class="upload_band_label" for="band_picture">Band Picture URL: </label>
    <input id="band_picture" type="text" name="band[image]" value="<%= @band.image %>">
  </p>

  <br>

  <input class="button" type="submit" value="<%= submission %>">
</form>

music_app/app/views/bands/edit.html.erb
<%= render 'form', editing: true, band: @band %>

music_app/app/views/bands/index.html.erb
<div class="band_pictures">
  <% Band.all.each do |band| %>
    <div class="display_under">
      <img class="format_image" src="<%= band.image %>" alt="">
      <a href="#"><%= band.name %></a>
      <span>
        <a href="<%= edit_band_url(band.id) %>">Edit</a> |
        <a href="<%= band_url(band.id) %>">Remove</a>
      </span>
    </div>
  <% end %>
</div>

music_app/app/views/bands/new.html.erb
<%= render 'form', editing: false, band: @band %>

music_app/app/views/bands/show.html.erb
<h3><%= @band.name %></h3>

<img src="<%= @band.image %>" alt="">

music_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <a class="home" href="<%= bands_url %>">
      <h1>Music App</h1>
    </a>

    <% if current_user %>
      <h1>Logged in as: <%= current_user.email %></h1>
      <form action="<%= session_url %>" method="post">
        <input type="hidden" name="_method" value="delete">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
        <input type="submit" name="" value="Log Out">
      </form>
    <% end %>

    <%= yield %>

  </body>
</html>

music_app/app/views/users/new.html.erb
<% if flash[:errors] %>
<ul>
  <% flash[:errors].each do |error| %>
  <li><%= error %></li>
  <% end %>
</ul>
<% end %>

<h3>New User</h3>

<a class="button" href="<%= new_session_url %>">Go to Sign-in</a>

<form action="<%= users_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token  %>">

  <p>
    <label class="sign_in_label" for="user_email">Email</label>
    <input id="user_email" type="email" name="user[email]" value="<%= @user.email %>">
  </p>

  <br><br>

  <p>
    <label class="sign_in_label" for="user_password">Password</label>
    <input id="user_password" type="password" name="user[password]" value="">
  </p>

  <br>

  <input class="button" type="submit" value="Submit">
</form>

music_app/app/views/users/show.html.erb
<h1><%= @user.email %></h1>